AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  CreateApex:
    Type: String
  HostedZoneId:
    Type: String

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - - Ref: DomainName
          - Ref: AWS::NoValue
      DomainValidationOptions:
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
